"""The one orchestrator: Document -> OCR -> Sanitization ->
AI Step Generation -> Validation -> Excel Export, in that exact order.

This is the approved security boundary (Architect decision #2): every
piece of text that reaches step_generator.py has been through
sanitize_text() first, and raw EvidenceItem (which carries image
bytes) never leaves this function.
"""
from .document_reader import extract_evidence
from .excel_exporter import export_to_excel
from .llm_provider import LLMProvider
from .models import GenerationResult, SanitizationReport, SanitizedEvidenceItem
from .ocr import detect_cursor_hint, extract_text
from .sanitizer import sanitize_text
from .step_generator import generate_test_steps
from .validator import validate_steps


def run(input_path: str, output_dir: str, llm_provider: LLMProvider) -> GenerationResult:
    evidence_items = extract_evidence(input_path)

    run_warnings: list[str] = []
    if not evidence_items:
        run_warnings.append("No screenshots were found in the source document.")

    aggregate_report = SanitizationReport()
    sanitized_items: list[SanitizedEvidenceItem] = []

    for item in evidence_items:
        try:
            item.ocr_text = extract_text(item.image_bytes)
        except Exception as exc:  # a single bad image shouldn't kill the run
            run_warnings.append(f"{item.source_ref}: OCR failed ({exc})")
            item.ocr_text = ""

        try:
            item.cursor_hint = detect_cursor_hint(item.image_bytes)
        except Exception as exc:
            run_warnings.append(
                f"{item.source_ref}: cursor-hint detection failed ({exc})"
            )
            item.cursor_hint = None

        sanitized_notes, notes_report = sanitize_text(item.notes_text)
        sanitized_ocr, ocr_report = sanitize_text(item.ocr_text)
        aggregate_report = aggregate_report.merge(notes_report).merge(ocr_report)

        # cursor_hint.description is synthetic (pixel coordinates + image
        # dimensions generated by ocr.py, never text read off the
        # screenshot) so it carries no PII risk and doesn't need
        # sanitize_text() -- unlike notes_text/ocr_text above.
        sanitized_items.append(
            SanitizedEvidenceItem(
                order=item.order,
                sanitized_notes=sanitized_notes,
                sanitized_ocr_text=sanitized_ocr,
                cursor_hint=item.cursor_hint,
                source_ref=item.source_ref,
            )
        )

    draft_steps = generate_test_steps(sanitized_items, llm_provider)
    validated_steps = validate_steps(draft_steps)

    result = GenerationResult(
        source_document=input_path,
        steps=validated_steps,
        sanitization_summary=aggregate_report,
        run_warnings=run_warnings,
    )

    result.output_path = export_to_excel(result, output_dir)

    return result
